# Cloud Build configuration for WhyTheyBuy Backend
# This file defines the CI/CD pipeline for building and deploying to Cloud Run

substitutions:
  _SERVICE_NAME: whytheybuy-api
  _REGION: us-central1
  _REDIS_HOST: ""  # Set via trigger or override
  _CLOUD_SQL_INSTANCE: ""  # Set to your Cloud SQL instance connection name

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/whytheybuy/api:${COMMIT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/whytheybuy/api:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'backend'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/whytheybuy/api:${COMMIT_SHA}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/whytheybuy/api:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/whytheybuy/api:${COMMIT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--timeout=300'
      - '--concurrency=80'
      - '--vpc-connector=whytheybuy-connector'
      - '--add-cloudsql-instances=${_CLOUD_SQL_INSTANCE}'
      - '--set-env-vars=GCP_PROJECT_ID=${PROJECT_ID}'
      - '--set-env-vars=GCP_REGION=${_REGION}'
      - '--set-env-vars=USE_CLOUD_SQL_CONNECTOR=true'
      - '--set-env-vars=CLOUD_SQL_INSTANCE_CONNECTION_NAME=${_CLOUD_SQL_INSTANCE}'
      - '--set-env-vars=DB_USER=postgres'
      - '--set-env-vars=DB_NAME=whytheybuy'
      - '--set-env-vars=REDIS_HOST=${_REDIS_HOST}'
      - '--set-env-vars=REDIS_PORT=6379'
      - '--set-env-vars=AI_PROVIDER=gemini'
      - '--set-env-vars=AI_MODEL=gemini-3-flash-preview'
      - '--set-env-vars=DEBUG=false'
      - '--set-secrets=JWT_SECRET_KEY=jwt-secret-key:latest'
      - '--set-secrets=DB_PASS=db-password:latest'
      - '--set-secrets=GEMINI_API_KEY=gemini-api-key:latest'

# Store images in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/whytheybuy/api:${COMMIT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/whytheybuy/api:latest'

# Build timeout
timeout: '1800s'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
